import { ReflexZone } from '../types';
import { ZoneColors } from './colors';

// ─── FOOT ZONES ───────────────────────────────────────────────────────────────
// x, y coordinates are normalized [0-1] relative to a 200×400 foot SVG viewport
// (0,0) = top-left, (1,1) = bottom-right
// Zones are placed on LEFT foot; right foot mirrors x-axis

export const FOOT_ZONES: ReflexZone[] = [
  {
    id: 'brain',
    area: 'foot',
    organ: 'Beyin / Brain',
    emoji: '🧠',
    color: ZoneColors.brain.base,
    glowColor: ZoneColors.brain.glow,
    pressureDuration: 60,
    x: 0.50, y: 0.05, r: 14,
    symptoms: ['baş ağrısı', 'headache', 'migraine', 'migren', 'konsantrasyon', 'concentration', 'hafıza', 'memory'],
    relatedZones: ['pituitary', 'sinus', 'neck'],
    tr: {
      name: 'Beyin',
      location: 'Baş parmağın üst kısmı, tırnak dibi',
      benefits: ['Baş ağrısı ve migren rahatlaması', 'Konsantrasyon artışı', 'Hafıza güçlendirme', 'Stres azaltma', 'Uyku kalitesini iyileştirme'],
      technique: 'Baş parmak yürüyüşü: Başparmağınızla küçük, kıl kıl hareketlerle parmak ucundan aşağıya doğru ilerleyin. 60 saniye boyunca sabit ve orta basınç uygulayın.',
      caution: 'Baş ağrısı devam ederse doktora başvurun.',
      description: 'Beyin refleks bölgesi, ayağın baş parmağının üst kısmında yer alır. Beynin sağ yarısı sol ayağa, sol yarısı sağ ayağa karşılık gelir.',
    },
    en: {
      name: 'Brain',
      location: 'Top of big toe, below the nail',
      benefits: ['Headache and migraine relief', 'Improved concentration', 'Memory enhancement', 'Stress reduction', 'Better sleep quality'],
      technique: 'Thumb walking: Use your thumb to make small caterpillar movements from the tip of the toe downward. Apply steady, medium pressure for 60 seconds.',
      caution: 'Consult a doctor if headaches persist.',
      description: 'The brain reflex zone is located on the top of the big toe. The right brain corresponds to the left foot and vice versa.',
    },
  },
  {
    id: 'pituitary',
    area: 'foot',
    organ: 'Hipofiz Bezi / Pituitary Gland',
    emoji: '⚡',
    color: ZoneColors.pituitary.base,
    glowColor: ZoneColors.pituitary.glow,
    pressureDuration: 45,
    x: 0.50, y: 0.08, r: 8,
    symptoms: ['hormon', 'hormone', 'denge', 'balance', 'tiroit', 'thyroid', 'büyüme', 'growth'],
    relatedZones: ['brain', 'neck'],
    tr: {
      name: 'Hipofiz Bezi',
      location: 'Baş parmağın ortası, tam merkezinde küçük nokta',
      benefits: ['Hormonal denge', 'Tiroit bezi düzenlemesi', 'Büyüme hormonu desteği', 'Uyku-uyanıklık döngüsü', 'Sindirim sistemi düzenlemesi'],
      technique: 'Döndürme tekniği: Başparmağınızın tam ortasındaki küçük noktaya baş parmak ucunuzu yerleştirin ve küçük döngüsel hareketler yapın. 45 saniye sürdürün.',
      caution: 'Hipofiz hastalığı olanlar önce doktora danışmalı.',
      description: 'Hipofiz bezi vücudun ana endokrin bezi olarak tüm hormonal sistemi düzenler. Bu nokta çok küçük ama çok etkilidir.',
    },
    en: {
      name: 'Pituitary Gland',
      location: 'Center of big toe pad, the small central point',
      benefits: ['Hormonal balance', 'Thyroid regulation', 'Growth hormone support', 'Sleep-wake cycle regulation', 'Digestive system regulation'],
      technique: 'Rotation technique: Place your thumb tip precisely on the center point of the big toe and make small circular movements. Hold for 45 seconds.',
      caution: 'Those with pituitary disorders should consult a doctor first.',
      description: 'The pituitary gland is the master endocrine gland that regulates all hormonal systems in the body.',
    },
  },
  {
    id: 'sinus',
    area: 'foot',
    organ: 'Sinüs / Sinuses',
    emoji: '🫁',
    color: ZoneColors.sinus.base,
    glowColor: ZoneColors.sinus.glow,
    pressureDuration: 45,
    x: 0.45, y: 0.12, r: 10,
    symptoms: ['sinüzit', 'sinusitis', 'burun', 'nose', 'tıkanıklık', 'congestion', 'alerji', 'allergy'],
    relatedZones: ['brain', 'neck'],
    tr: {
      name: 'Sinüsler',
      location: 'Küçük parmakların üst bölgesi ve yanlı kısımları',
      benefits: ['Sinüs tıkanıklığını açma', 'Alerjik rinit rahatlaması', 'Baş ağrısı geçirme', 'Solunum kolaylaştırma', 'Koku alma iyileştirme'],
      technique: 'Parmak yürüyüşü: Her küçük parmağı uçtan aşağıya doğru işaret parmağınızla yürüyün. Her parmak için 15 saniye, toplamda 45 saniye.',
      caution: 'Akut sinüzit enfeksiyonunda refleksoloji ek tedavi olarak kullanılabilir.',
      description: 'Sinüs refleks bölgeleri, baş parmak dışındaki tüm parmakların üst kısımlarında yer alır.',
    },
    en: {
      name: 'Sinuses',
      location: 'Top sections and sides of all smaller toes',
      benefits: ['Sinus congestion relief', 'Allergic rhinitis relief', 'Headache reduction', 'Easier breathing', 'Improved sense of smell'],
      technique: 'Finger walking: Walk your index finger from tip to base of each smaller toe. 15 seconds per toe, 45 seconds total.',
      caution: 'Reflexology can be used as supplementary treatment during acute sinusitis.',
      description: 'Sinus reflex zones are located on the top portions of all toes except the big toe.',
    },
  },
  {
    id: 'neck',
    area: 'foot',
    organ: 'Boyun / Neck',
    emoji: '🦢',
    color: ZoneColors.neck.base,
    glowColor: ZoneColors.neck.glow,
    pressureDuration: 60,
    x: 0.50, y: 0.17, r: 11,
    symptoms: ['boyun', 'neck', 'boyun ağrısı', 'neck pain', 'sertlik', 'stiffness', 'omuz', 'shoulder'],
    relatedZones: ['brain', 'spine'],
    tr: {
      name: 'Boyun ve Servikal Bölge',
      location: 'Baş parmağın alt kısmı ve kök bölgesi',
      benefits: ['Boyun ağrısı azaltma', 'Baş dönmesi giderme', 'Omuz gerginliği rahatlatma', 'Boyun esnekliği artırma', 'Uyuşma ve karıncalanma azaltma'],
      technique: 'Döndürme ve basınç: Baş parmağın kökünü tutup nazikçe döndürün, ardından başparmak yürüyüşü ile aşağı inin. 60 saniye sürdürün.',
      caution: 'Boyun yaralanması veya boyun fıtığında mutlaka doktora danışın.',
      description: 'Boyun refleks bölgesi, baş parmağın alt kısmında yer alır ve servikal omurları temsil eder.',
    },
    en: {
      name: 'Neck & Cervical Region',
      location: 'Base of big toe and its root area',
      benefits: ['Neck pain relief', 'Dizziness reduction', 'Shoulder tension release', 'Improved neck flexibility', 'Reduced numbness and tingling'],
      technique: 'Rotation and pressure: Gently rotate the base of the big toe, then thumb-walk downward. Maintain for 60 seconds.',
      caution: 'Consult a doctor for neck injuries or herniated discs.',
      description: 'The neck reflex zone is at the base of the big toe and represents the cervical vertebrae.',
    },
  },
  {
    id: 'lung',
    area: 'foot',
    organ: 'Akciğer / Lung',
    emoji: '🫁',
    color: ZoneColors.lung.base,
    glowColor: ZoneColors.lung.glow,
    pressureDuration: 60,
    x: 0.40, y: 0.26, r: 14,
    symptoms: ['akciğer', 'lung', 'nefes', 'breathing', 'öksürük', 'cough', 'astım', 'asthma', 'bronşit', 'bronchitis'],
    relatedZones: ['heart', 'neck'],
    tr: {
      name: 'Akciğer ve Bronşlar',
      location: 'Ayak tabanının üst üçte birinde, metatarsal kemikler bölgesi',
      benefits: ['Solunum kolaylaştırma', 'Astım semptomları rahatlatma', 'Bronşiyal gerginlik azaltma', 'Bağışıklık sistemi güçlendirme', 'Öksürük azaltma'],
      technique: 'Başparmak yürüyüşü: Parmakların hemen altından başlayarak yatay çizgiler halinde ilerleyin. Her satırda 10 saniye, 6 satır halinde.',
      caution: 'Ciddi solunum sorunlarında acil tıbbi yardım alın. Refleksoloji destekleyicidir.',
      description: 'Akciğer refleks bölgesi, metatarsal kemiklerin bulunduğu ayak tabanının üst kısmında, parmakların hemen altında yer alır.',
    },
    en: {
      name: 'Lung & Bronchi',
      location: 'Upper third of foot sole, metatarsal bone area',
      benefits: ['Easier breathing', 'Asthma symptom relief', 'Reduced bronchial tension', 'Immune system boost', 'Cough reduction'],
      technique: 'Thumb walking: Begin just below the toes and walk in horizontal rows. 10 seconds per row, 6 rows total.',
      caution: 'For serious breathing difficulties, seek emergency medical help. Reflexology is supportive only.',
      description: 'The lung reflex zone is in the upper area of the foot sole at the metatarsal bones, just below the toes.',
    },
  },
  {
    id: 'heart',
    area: 'foot',
    organ: 'Kalp / Heart',
    emoji: '❤️',
    color: ZoneColors.heart.base,
    glowColor: ZoneColors.heart.glow,
    pressureDuration: 45,
    x: 0.30, y: 0.28, r: 11,
    symptoms: ['kalp', 'heart', 'tansiyon', 'blood pressure', 'çarpıntı', 'palpitation', 'dolaşım', 'circulation'],
    relatedZones: ['lung', 'kidney'],
    tr: {
      name: 'Kalp',
      location: 'Sol ayakta 4-5. metatarsal kemik arası, orta bölge üst kısmı (sadece sol ayakta)',
      benefits: ['Kan basıncı düzenleme', 'Dolaşım iyileştirme', 'Çarpıntı azaltma', 'Stres kaynaklı kalp gerginliği rahatlatma', 'Enerji artırma'],
      technique: 'Nazik basınç ve tutma: Orta basınçla 3 saniye bas, 3 saniye bırak. Bu ritmi 45 saniye sürdürün. Çok kuvvetli basmaktan kaçının.',
      caution: 'Kalp hastalığı olanlar mutlaka doktora danışmalı. Çok güçlü basınç uygulamayın.',
      description: 'Kalp refleks bölgesi sadece sol ayakta bulunur. Sol ayağın orta bölgesinde, 4. ve 5. metatarsal kemikler arasındadır.',
    },
    en: {
      name: 'Heart',
      location: 'Left foot only — between 4th-5th metatarsal, upper middle area',
      benefits: ['Blood pressure regulation', 'Improved circulation', 'Palpitation reduction', 'Stress-related heart tension relief', 'Energy boost'],
      technique: 'Gentle pressure and hold: Press with medium pressure for 3 seconds, release for 3 seconds. Maintain this rhythm for 45 seconds. Avoid heavy pressure.',
      caution: 'Those with heart disease must consult a doctor. Do not apply strong pressure.',
      description: 'The heart reflex zone is only on the left foot, in the middle area between the 4th and 5th metatarsal bones.',
    },
  },
  {
    id: 'stomach',
    area: 'foot',
    organ: 'Mide / Stomach',
    emoji: '🌿',
    color: ZoneColors.stomach.base,
    glowColor: ZoneColors.stomach.glow,
    pressureDuration: 60,
    x: 0.45, y: 0.40, r: 13,
    symptoms: ['mide', 'stomach', 'sindirim', 'digestion', 'bulantı', 'nausea', 'hazımsızlık', 'indigestion', 'reflü', 'reflux'],
    relatedZones: ['liver', 'intestine'],
    tr: {
      name: 'Mide',
      location: 'Ayak kemeri başlangıcı, 1. metatarsal altı iç bölge',
      benefits: ['Hazımsızlık rahatlatma', 'Bulantı giderme', 'Reflü azaltma', 'Midedeki gaz ve şişkinlik giderme', 'İştah düzenleme'],
      technique: 'Sabit basınç ve döngüsel hareket: Başparmak ucuyla orta basınç uygulayarak küçük daireler çizin. 60 saniye boyunca devam edin.',
      caution: 'Mide ülseri olan kişiler dikkatli olmalı, çok kuvvetli basmaktan kaçınmalı.',
      description: 'Mide refleks bölgesi, ayak kemerinin başladığı noktanın üst iç kısmında yer alır.',
    },
    en: {
      name: 'Stomach',
      location: 'Beginning of the arch, inner upper area below 1st metatarsal',
      benefits: ['Indigestion relief', 'Nausea relief', 'Acid reflux reduction', 'Gas and bloating relief', 'Appetite regulation'],
      technique: 'Steady pressure with circular movement: Use thumb tip to draw small circles with medium pressure. Continue for 60 seconds.',
      caution: 'Those with stomach ulcers should be careful and avoid excessive pressure.',
      description: 'The stomach reflex zone is at the upper inner portion of the arch beginning.',
    },
  },
  {
    id: 'liver',
    area: 'foot',
    organ: 'Karaciğer / Liver',
    emoji: '🍃',
    color: ZoneColors.liver.base,
    glowColor: ZoneColors.liver.glow,
    pressureDuration: 60,
    x: 0.60, y: 0.42, r: 13,
    symptoms: ['karaciğer', 'liver', 'safra', 'bile', 'detoks', 'detox', 'yorgunluk', 'fatigue', 'sarılık', 'jaundice'],
    relatedZones: ['stomach', 'kidney'],
    tr: {
      name: 'Karaciğer ve Safra Kesesi',
      location: 'Sağ ayakta, 3-4. metatarsal altı orta bölge (sadece sağ ayakta)',
      benefits: ['Detoksifikasyon desteği', 'Sindirim iyileştirme', 'Yorgunluk giderme', 'Safra salgısı düzenleme', 'Metabolizma desteği'],
      technique: 'Başparmak yürüyüşü: Bölge üzerinde yatay ve dikey yürüyüş hareketleri yapın. Her yön için 30 saniye.',
      caution: 'Karaciğer hastalığı olanlar refleksoloji öncesi doktora danışmalı.',
      description: 'Karaciğer refleks bölgesi sadece sağ ayakta bulunur ve orta bölge üst kısmında yer alır.',
    },
    en: {
      name: 'Liver & Gallbladder',
      location: 'Right foot only — below 3rd-4th metatarsal, middle area',
      benefits: ['Detoxification support', 'Improved digestion', 'Fatigue reduction', 'Bile secretion regulation', 'Metabolism support'],
      technique: 'Thumb walking: Make horizontal and vertical walking movements over the zone. 30 seconds in each direction.',
      caution: 'Those with liver disease should consult a doctor before reflexology.',
      description: 'The liver reflex zone is only on the right foot, in the upper portion of the middle area.',
    },
  },
  {
    id: 'kidney',
    area: 'foot',
    organ: 'Böbrek / Kidney',
    emoji: '💧',
    color: ZoneColors.kidney.base,
    glowColor: ZoneColors.kidney.glow,
    pressureDuration: 60,
    x: 0.47, y: 0.50, r: 11,
    symptoms: ['böbrek', 'kidney', 'idrar', 'urine', 'ödem', 'edema', 'sırt ağrısı', 'back pain', 'tansyion', 'blood pressure'],
    relatedZones: ['stomach', 'intestine'],
    tr: {
      name: 'Böbrek',
      location: 'Ayak tabanının ortası, kemerin tam merkezinde',
      benefits: ['Vücut sıvı dengesini düzenleme', 'Ödem azaltma', 'Sırt ağrısı rahatlatma', 'Kan basıncı desteği', 'Detoksifikasyon'],
      technique: 'Kanca tekniği ve döngüsel hareket: Başparmak ucuyla bulduğunuz hassas noktaya kanca gibi uygulama yapın. 5 saniye bas, 5 saniye bırak. 60 saniye sürdürün.',
      caution: 'Kronik böbrek hastalığında kesinlikle doktora danışın.',
      description: 'Böbrek refleks bölgesi, ayak tabanının tam ortasında yer alır — sol böbrek sol ayakta, sağ böbrek sağ ayakta.',
    },
    en: {
      name: 'Kidney',
      location: 'Center of foot sole, exact middle of the arch',
      benefits: ['Body fluid balance regulation', 'Edema reduction', 'Back pain relief', 'Blood pressure support', 'Detoxification'],
      technique: 'Hook technique with circular movement: Apply hook-like pressure with thumb tip on the sensitive point. 5 sec press, 5 sec release. 60 seconds total.',
      caution: 'Absolutely consult a doctor for chronic kidney disease.',
      description: 'The kidney reflex zone is at the exact center of the foot sole — left kidney on left foot, right kidney on right foot.',
    },
  },
  {
    id: 'intestine',
    area: 'foot',
    organ: 'Bağırsak / Intestines',
    emoji: '🌱',
    color: ZoneColors.intestine.base,
    glowColor: ZoneColors.intestine.glow,
    pressureDuration: 90,
    x: 0.50, y: 0.60, r: 16,
    symptoms: ['bağırsak', 'intestine', 'kabızlık', 'constipation', 'ishal', 'diarrhea', 'IBS', 'şişkinlik', 'bloating'],
    relatedZones: ['stomach', 'kidney'],
    tr: {
      name: 'İnce ve Kalın Bağırsak',
      location: 'Ayak tabanının alt yarısı, topuk üzeri geniş bölge',
      benefits: ['Kabızlık rahatlatma', 'Bağırsak hareketlerini düzenleme', 'Şişkinlik giderme', 'IBS semptomlarını azaltma', 'Sindirim iyileştirme'],
      technique: 'Saat yönünde döngüsel başparmak yürüyüşü: Bölgenin dışından başlayarak saat yönünde spiral hareketlerle merkeze doğru ilerleyin. 90 saniye.',
      caution: 'Akut karın ağrısında mutlaka doktora başvurun.',
      description: 'Bağırsak refleks bölgesi, ayak tabanının alt yarısında geniş bir alan kaplar. İnce bağırsak iç kısımda, kalın bağırsak ise daha geniş dış alanda yer alır.',
    },
    en: {
      name: 'Small & Large Intestines',
      location: 'Lower half of foot sole, broad area above the heel',
      benefits: ['Constipation relief', 'Bowel movement regulation', 'Bloating relief', 'IBS symptom reduction', 'Improved digestion'],
      technique: 'Clockwise circular thumb walking: Start from the outer edge and spiral inward in a clockwise direction. 90 seconds.',
      caution: 'Seek immediate medical attention for acute abdominal pain.',
      description: 'The intestinal reflex zone covers a large area in the lower half of the foot sole.',
    },
  },
  {
    id: 'spine',
    area: 'foot',
    organ: 'Omurga / Spine',
    emoji: '🦴',
    color: ZoneColors.spine.base,
    glowColor: ZoneColors.spine.glow,
    pressureDuration: 90,
    x: 0.15, y: 0.45, r: 8,
    symptoms: ['omurga', 'spine', 'bel', 'lower back', 'sırt', 'back', 'fıtık', 'herniation', 'skolyoz', 'scoliosis'],
    relatedZones: ['kidney', 'sciatic'],
    tr: {
      name: 'Omurga (Tüm Vertebralar)',
      location: 'Ayağın iç kenarı boyunca — parmak kökünden topuğa kadar',
      benefits: ['Sırt ağrısı rahatlatma', 'Omurga esnekliği artırma', 'Sinir ağrısı azaltma', 'Bel ağrısı giderme', 'Duruş iyileştirme'],
      technique: 'Omurga boyunca başparmak yürüyüşü: İç kenarı boyunca parmak kökünden topuğa doğru yavaşça ilerleyin. Hassas noktaları bulup 10 saniye basın. Toplam 90 saniye.',
      caution: 'Omurga cerrahisi geçirenler veya disk hernisi olanlar doktora danışmalı.',
      description: 'Omurga refleks bölgesi, ayağın iç kenarı boyunca uzanır. Parmak kısmı servikal, orta kısım torakal, alt kısım lumbar, topuk ise sakral vertebraları temsil eder.',
    },
    en: {
      name: 'Spine (All Vertebrae)',
      location: 'Along the inner edge of the foot — from toe base to heel',
      benefits: ['Back pain relief', 'Improved spinal flexibility', 'Nerve pain reduction', 'Lower back pain relief', 'Posture improvement'],
      technique: 'Thumb walking along spine: Slowly walk along the inner edge from toe base toward heel. Find sensitive spots and press for 10 seconds. Total 90 seconds.',
      caution: 'Those with spinal surgery or disc herniation should consult a doctor.',
      description: 'The spine reflex zone runs along the entire inner edge of the foot. Toe area = cervical, middle = thoracic, lower = lumbar, heel = sacral vertebrae.',
    },
  },
  {
    id: 'sciatic',
    area: 'foot',
    organ: 'Siyatik Sinir / Sciatic Nerve',
    emoji: '⚡',
    color: ZoneColors.sciatic.base,
    glowColor: ZoneColors.sciatic.glow,
    pressureDuration: 60,
    x: 0.50, y: 0.85, r: 12,
    symptoms: ['siyatik', 'sciatic', 'bacak ağrısı', 'leg pain', 'uyuşma', 'numbness', 'karıncalanma', 'tingling'],
    relatedZones: ['spine', 'kidney'],
    tr: {
      name: 'Siyatik Sinir',
      location: 'Topuk ortasından biraz yukarı, arka topuk bölgesi',
      benefits: ['Siyatik sinir ağrısı azaltma', 'Bacak uyuşması giderme', 'Alt sırt ağrısı rahatlatma', 'Karıncalanma azaltma', 'Sinir iletimini destekleme'],
      technique: 'Kanca basıncı: Topuğun arka üst kenarına başparmakla kanca şeklinde baskı uygulayın. 5 saniye bas, nefes ver, bırak. 60 saniye sürdürün.',
      caution: 'Şiddetli siyatik ağrısında nöroloji uzmanına başvurun.',
      description: 'Siyatik sinir refleks bölgesi topukta yer alır. L4-S3 sinir kökleriyle ilişkili bu nokta, sinir kaynaklı ağrılarda çok etkilidir.',
    },
    en: {
      name: 'Sciatic Nerve',
      location: 'Slightly above center of heel, back heel area',
      benefits: ['Sciatic nerve pain reduction', 'Leg numbness relief', 'Lower back pain relief', 'Tingling reduction', 'Nerve conduction support'],
      technique: 'Hook pressure: Apply hook-like thumb pressure on the upper back edge of the heel. 5 sec press, breathe out, release. 60 seconds total.',
      caution: 'Consult a neurologist for severe sciatica.',
      description: 'The sciatic nerve reflex zone is located in the heel. Related to L4-S3 nerve roots, this point is highly effective for nerve-related pain.',
    },
  },
  {
    id: 'uterus_ovary',
    area: 'foot',
    organ: 'Üreme Sistemi / Reproductive System',
    emoji: '🌸',
    color: ZoneColors.uterus.base,
    glowColor: ZoneColors.uterus.glow,
    pressureDuration: 45,
    x: 0.20, y: 0.82, r: 10,
    symptoms: ['adet', 'menstrual', 'kramp', 'cramp', 'over', 'ovary', 'hormonal', 'PMS', 'menopoz', 'menopause'],
    relatedZones: ['kidney', 'sciatic'],
    tr: {
      name: 'Rahim ve Yumurtalıklar / Üreme Sistemi',
      location: 'Topuğun iç tarafı (rahim) ve dış tarafı (yumurtalık)',
      benefits: ['Adet krampları azaltma', 'PMS semptomları rahatlatma', 'Hormonal denge', 'Menopoz semptomları azaltma', 'Üreme sağlığı desteği'],
      technique: 'Parmak döndürme ve basınç: İç ve dış topuk bölgelerine işaret parmağıyla nazikçe döngüsel basınç uygulayın. 45 saniye, her iki taraf.',
      caution: 'Hamilelikte topuk bölgesine basınç uygulamayın.',
      description: 'Üreme sistemi refleks bölgeleri topuğun her iki yanında yer alır. İç topuk rahim, dış topuk yumurtalıkları temsil eder.',
    },
    en: {
      name: 'Uterus & Ovaries / Reproductive System',
      location: 'Inner heel (uterus) and outer heel (ovaries)',
      benefits: ['Menstrual cramp reduction', 'PMS symptom relief', 'Hormonal balance', 'Menopause symptom reduction', 'Reproductive health support'],
      technique: 'Finger rotation and pressure: Gently apply circular pressure with index finger on both inner and outer heel areas. 45 seconds, both sides.',
      caution: 'Do not apply pressure to the heel area during pregnancy.',
      description: 'Reproductive system reflex zones are on both sides of the heel. Inner heel = uterus, outer heel = ovaries.',
    },
  },
];

// ─── EAR ZONES ────────────────────────────────────────────────────────────────

export const EAR_ZONES: ReflexZone[] = [
  {
    id: 'shen_men',
    area: 'ear',
    organ: 'Shen Men — Master Calm Point',
    emoji: '🌙',
    color: ZoneColors.shenmen.base,
    glowColor: ZoneColors.shenmen.glow,
    pressureDuration: 90,
    x: 0.65, y: 0.25, r: 10,
    symptoms: ['stres', 'stress', 'anksiyete', 'anxiety', 'ağrı', 'pain', 'uyku', 'sleep', 'panik', 'panic'],
    relatedZones: ['ear_spine', 'ear_eye'],
    tr: {
      name: 'Shen Men (İlahi Kapı)',
      location: 'Kulak kıkırdağının üst üçte birinde, kulak antiheliksinin üst çatallanan noktası',
      benefits: ['Stres ve anksiyete anında azaltma', 'Ağrı kesici etki', 'Derin uyku desteği', 'Panik atağı yatıştırma', 'Genel rahatlama ve huzur'],
      technique: 'Sıkıştırma ve tutma: Shen Men noktasını başparmak ve işaret parmağı arasında nazikçe sıkıştırın. 5 saniye tut, 2 saniye bırak. 90 saniye boyunca tekrarlayın.',
      caution: 'Kulak enfeksiyonu veya yarasında uygulamayın.',
      description: 'Shen Men, auriculoterapinin en önemli noktasıdır. Kulak kıkırdağının üst kısmında yer alır ve anında sakinleştirici etkisiyle bilinir.',
    },
    en: {
      name: 'Shen Men (Divine Gate)',
      location: 'Upper third of ear cartilage, top bifurcation of the antihelix',
      benefits: ['Instant stress and anxiety reduction', 'Analgesic effect', 'Deep sleep support', 'Panic attack calming', 'General relaxation and peace'],
      technique: 'Pinching and holding: Gently pinch Shen Men between thumb and index finger. Hold 5 seconds, release 2 seconds. Repeat for 90 seconds.',
      caution: 'Do not apply during ear infection or injury.',
      description: 'Shen Men is the most important point in auriculotherapy. Located in the upper cartilage, it is known for its immediate calming effect.',
    },
  },
  {
    id: 'ear_spine',
    area: 'ear',
    organ: 'Kulak Omurga / Ear Spine',
    emoji: '🦴',
    color: ZoneColors.spine.base,
    glowColor: ZoneColors.spine.glow,
    pressureDuration: 60,
    x: 0.50, y: 0.40, r: 9,
    symptoms: ['sırt', 'back', 'bel', 'lumbar', 'boyun', 'neck', 'omurga', 'spine'],
    relatedZones: ['shen_men'],
    tr: {
      name: 'Kulak Omurga Bölgesi',
      location: 'Antiheliksın yay şeklindeki kıvrımı boyunca, kulağın ortası',
      benefits: ['Sırt ve bel ağrısı rahatlatma', 'Omurga gerginliği azaltma', 'Boyun ağrısı giderme', 'Postür desteği'],
      technique: 'Tırnak ucu ile yürüyüş: Antiheliksin kıvrımı boyunca üstten aşağıya doğru yavaşça yürüyün. 60 saniye.',
      caution: 'Çok güçlü basınçtan kaçının.',
      description: 'Antiheliksin kavisli kıvrımı boyunca uzanan omurga refleks bölgesi, farklı seviyelerde vertebraları temsil eder.',
    },
    en: {
      name: 'Ear Spine Zone',
      location: 'Along the curved antihelix ridge, middle of ear',
      benefits: ['Back and lower back pain relief', 'Spinal tension reduction', 'Neck pain relief', 'Posture support'],
      technique: 'Nail-tip walking: Slowly walk from top to bottom along the antihelix curve. 60 seconds.',
      caution: 'Avoid excessive pressure.',
      description: 'The spine reflex zone runs along the curved ridge of the antihelix, representing vertebrae at different levels.',
    },
  },
  {
    id: 'ear_eye',
    area: 'ear',
    organ: 'Kulak Göz / Eye Auricular',
    emoji: '👁️',
    color: ZoneColors.sinus.base,
    glowColor: ZoneColors.sinus.glow,
    pressureDuration: 45,
    x: 0.30, y: 0.80, r: 8,
    symptoms: ['göz', 'eye', 'göz yorgunluğu', 'eye strain', 'baş ağrısı', 'headache'],
    relatedZones: ['shen_men'],
    tr: {
      name: 'Göz (Kulak Noktası)',
      location: 'Kulak memesinin üst kısmı',
      benefits: ['Göz yorgunluğu giderme', 'Görme netliği', 'Ekran kaynaklı baş ağrısı azaltma'],
      technique: 'Nazik sıkıştırma: Kulak memesinin üst kısmını nazikçe sıkıştırın. 45 saniye.',
      caution: 'Çok güçlü basmayın.',
      description: 'Göz refleks noktası kulak memesinin üstünde yer alır.',
    },
    en: {
      name: 'Eye (Auricular Point)',
      location: 'Upper part of the earlobe',
      benefits: ['Eye fatigue relief', 'Visual clarity', 'Screen-related headache reduction'],
      technique: 'Gentle pinching: Gently pinch upper earlobe area. 45 seconds.',
      caution: 'Do not press too hard.',
      description: 'The eye reflex point is located at the top of the earlobe.',
    },
  },
  {
    id: 'ear_stomach',
    area: 'ear',
    organ: 'Kulak Mide / Ear Stomach',
    emoji: '🌿',
    color: ZoneColors.stomach.base,
    glowColor: ZoneColors.stomach.glow,
    pressureDuration: 60,
    x: 0.40, y: 0.55, r: 9,
    symptoms: ['mide', 'stomach', 'bulantı', 'nausea', 'sindirim', 'digestion'],
    relatedZones: ['shen_men', 'ear_spine'],
    tr: {
      name: 'Mide (Kulak Noktası)',
      location: 'Kulak concha (iç çukur) üst bölümü',
      benefits: ['Bulantı giderme', 'Mide ağrısı azaltma', 'Sindirim desteği', 'Yolculuk tutması yatıştırma'],
      technique: 'Döngüsel basınç: Concha içine işaret parmak ucuyla nazik dairesel hareketler yapın. 60 saniye.',
      caution: 'Şiddetli mide ağrısında doktora gidin.',
      description: 'Mide noktası kulağın iç çukurunda (concha) yer alır.',
    },
    en: {
      name: 'Stomach (Auricular Point)',
      location: 'Upper concha (inner cavity) of the ear',
      benefits: ['Nausea relief', 'Stomach pain reduction', 'Digestion support', 'Motion sickness relief'],
      technique: 'Circular pressure: Make gentle circular movements with index fingertip inside the concha. 60 seconds.',
      caution: 'Seek medical attention for severe stomach pain.',
      description: 'The stomach point is in the inner cavity (concha) of the ear.',
    },
  },
  {
    id: 'zero_point',
    area: 'ear',
    organ: 'Sıfır Nokta / Zero Point',
    emoji: '⭕',
    color: ZoneColors.kidney.base,
    glowColor: ZoneColors.kidney.glow,
    pressureDuration: 120,
    x: 0.55, y: 0.60, r: 10,
    symptoms: ['denge', 'balance', 'hormonal', 'genel', 'general', 'homeostaz', 'homeostasis'],
    relatedZones: ['shen_men'],
    tr: {
      name: 'Sıfır Nokta (Denge Noktası)',
      location: 'Kulak concha orta noktası',
      benefits: ['Vücut homeostazı (iç denge)', 'Tüm organları dengeleme', 'Genel enerji akışı', 'Stres tepkisini sıfırlama'],
      technique: 'Derin tutma: İşaret parmak ucuyla sabit basınç uygulayın ve nefes alırken tutun. 4 nefes döngüsü boyunca uygulayın.',
      caution: 'Çok hassas bir nokta, nazik basınç yeterlidir.',
      description: 'Sıfır nokta, vücudun tüm sistemlerini homeostaza döndürmeye yardımcı olan güçlü bir denge noktasıdır.',
    },
    en: {
      name: 'Zero Point (Balance Point)',
      location: 'Center of ear concha',
      benefits: ['Body homeostasis (internal balance)', 'Balancing all organs', 'General energy flow', 'Stress response reset'],
      technique: 'Deep holding: Apply steady pressure with index fingertip and hold while breathing. Apply for 4 breath cycles.',
      caution: 'Very sensitive point, gentle pressure is sufficient.',
      description: 'Zero point is a powerful balancing point that helps restore homeostasis to all body systems.',
    },
  },
];

// ─── MERGED ZONES MAP ─────────────────────────────────────────────────────────

export const ALL_ZONES: Record<string, ReflexZone> = [
  ...FOOT_ZONES,
  ...EAR_ZONES,
].reduce((acc, zone) => ({ ...acc, [zone.id]: zone }), {});

// ─── SYMPTOM MAP ──────────────────────────────────────────────────────────────

export const SYMPTOM_ZONE_MAP: Record<string, string[]> = {
  // Head & Nervous System
  'baş ağrısı':       ['brain', 'sinus', 'neck', 'shen_men'],
  'headache':         ['brain', 'sinus', 'neck', 'shen_men'],
  'migren':           ['brain', 'sinus', 'shen_men'],
  'migraine':         ['brain', 'sinus', 'shen_men'],
  'stres':            ['shen_men', 'kidney', 'zero_point', 'brain'],
  'stress':           ['shen_men', 'kidney', 'zero_point', 'brain'],
  'anksiyete':        ['shen_men', 'zero_point', 'brain'],
  'anxiety':          ['shen_men', 'zero_point', 'brain'],
  'uyku':             ['shen_men', 'brain', 'kidney', 'zero_point'],
  'sleep':            ['shen_men', 'brain', 'kidney', 'zero_point'],
  'yorgunluk':        ['kidney', 'liver', 'shen_men', 'zero_point'],
  'fatigue':          ['kidney', 'liver', 'shen_men', 'zero_point'],

  // Musculoskeletal
  'bel ağrısı':       ['spine', 'kidney', 'sciatic'],
  'back pain':        ['spine', 'kidney', 'sciatic'],
  'sırt ağrısı':      ['spine', 'sciatic'],
  'boyun ağrısı':     ['neck', 'spine'],
  'neck pain':        ['neck', 'spine'],
  'omuz':             ['neck', 'lung'],
  'shoulder':         ['neck', 'lung'],
  'siyatik':          ['sciatic', 'spine', 'kidney'],
  'sciatica':         ['sciatic', 'spine', 'kidney'],

  // Digestive
  'mide':             ['stomach', 'intestine'],
  'stomach':          ['stomach', 'intestine'],
  'bulantı':          ['stomach', 'ear_stomach'],
  'nausea':           ['stomach', 'ear_stomach'],
  'hazımsızlık':      ['stomach', 'liver'],
  'indigestion':      ['stomach', 'liver'],
  'kabızlık':         ['intestine', 'stomach'],
  'constipation':     ['intestine', 'stomach'],
  'sindirim':         ['stomach', 'intestine', 'liver'],
  'digestion':        ['stomach', 'intestine', 'liver'],
  'şişkinlik':        ['intestine', 'stomach'],
  'bloating':         ['intestine', 'stomach'],

  // Respiratory
  'nefes':            ['lung', 'sinus'],
  'breathing':        ['lung', 'sinus'],
  'astım':            ['lung', 'sinus'],
  'asthma':           ['lung', 'sinus'],
  'öksürük':          ['lung', 'sinus'],
  'cough':            ['lung', 'sinus'],
  'sinüzit':          ['sinus', 'lung'],
  'sinusitis':        ['sinus', 'lung'],

  // Circulatory
  'tansiyon':         ['heart', 'kidney'],
  'blood pressure':   ['heart', 'kidney'],
  'dolaşım':          ['heart', 'kidney'],
  'circulation':      ['heart', 'kidney'],

  // Urogenital
  'adet':             ['uterus_ovary', 'kidney'],
  'menstrual':        ['uterus_ovary', 'kidney'],
  'kramp':            ['uterus_ovary', 'intestine'],
  'cramp':            ['uterus_ovary', 'intestine'],
  'hormonal':         ['pituitary', 'uterus_ovary', 'kidney'],

  // Eye
  'göz':              ['ear_eye', 'sinus'],
  'eye':              ['ear_eye', 'sinus'],
  'göz yorgunluğu':   ['ear_eye'],
  'eye strain':       ['ear_eye'],

  // General wellness
  'enerji':           ['kidney', 'liver', 'zero_point'],
  'energy':           ['kidney', 'liver', 'zero_point'],
  'bağışıklık':       ['lung', 'kidney', 'intestine'],
  'immunity':         ['lung', 'kidney', 'intestine'],
  'genel':            ['zero_point', 'shen_men', 'kidney'],
  'general':          ['zero_point', 'shen_men', 'kidney'],
};

// ─── QUICK SESSIONS data ─────────────────────────────────────────────────────

export const SESSIONS_DATA = [
  {
    id: 'stress-relief',
    emoji: '🌊',
    category: 'stress',
    isPremium: false,
    durationMinutes: 10,
    difficulty: 'beginner',
    title: { tr: 'Stres Rahatlatma', en: 'Stress Relief' },
    description: { tr: 'Günlük stresi eritmek için 5 temel nokta', en: '5 key points to melt daily stress' },
    benefits: {
      tr: ['Anında rahatlama', 'Kortizol düşürme', 'Zihin sakinleştirme'],
      en: ['Instant relaxation', 'Cortisol reduction', 'Mind calming'],
    },
    steps: [
      { id: 's1', zoneId: 'shen_men',   durationSeconds: 90, instruction: { tr: 'Shen Men noktasını nazikçe sıkıştırın ve derin nefes alın', en: 'Gently pinch Shen Men point and breathe deeply' }},
      { id: 's2', zoneId: 'brain',      durationSeconds: 60, instruction: { tr: 'Baş parmak ucunu küçük daireler yaparak masaj yapın', en: 'Massage the big toe tip with small circles' }},
      { id: 's3', zoneId: 'kidney',     durationSeconds: 60, instruction: { tr: 'Ayak tabanı ortasına sakin basınç uygulayın', en: 'Apply calm pressure to center of foot sole' }},
      { id: 's4', zoneId: 'zero_point', durationSeconds: 120, instruction: { tr: 'Sıfır noktayı tutun ve vücudunuzun dengelenmesine izin verin', en: 'Hold zero point and let your body balance itself' }},
      { id: 's5', zoneId: 'spine',      durationSeconds: 90, instruction: { tr: 'İç kenar boyunca yavaşça tarayın', en: 'Slowly scan along inner edge' }},
    ],
  },
  {
    id: 'sleep-preparation',
    emoji: '🌙',
    category: 'sleep',
    isPremium: false,
    durationMinutes: 15,
    difficulty: 'beginner',
    title: { tr: 'Uyku Hazırlığı', en: 'Sleep Preparation' },
    description: { tr: 'Derin uyku için uyku öncesi seans', en: 'Pre-sleep session for deep rest' },
    benefits: {
      tr: ['Uyku kalitesi', 'Zihin sakinleştirme', 'Gece dinlenmesi'],
      en: ['Sleep quality', 'Mind calming', 'Night recovery'],
    },
    steps: [
      { id: 'sl1', zoneId: 'shen_men',   durationSeconds: 120, instruction: { tr: 'Shen Men\'i tutun — uyku kapınızı aralayın', en: 'Hold Shen Men — open your sleep door' }},
      { id: 'sl2', zoneId: 'brain',      durationSeconds: 60,  instruction: { tr: 'Beyin bölgesini yavaşça masaj yapın', en: 'Slowly massage the brain zone' }},
      { id: 'sl3', zoneId: 'kidney',     durationSeconds: 90,  instruction: { tr: 'Böbrek bölgesine rahatlatıcı basınç', en: 'Soothing pressure on kidney zone' }},
      { id: 'sl4', zoneId: 'zero_point', durationSeconds: 150, instruction: { tr: 'Sıfır noktada kalın, nefes alın, salın verin', en: 'Stay at zero point, breathe in, breathe out' }},
    ],
  },
  {
    id: 'energy-boost',
    emoji: '⚡',
    category: 'energy',
    isPremium: false,
    durationMinutes: 12,
    difficulty: 'intermediate',
    title: { tr: 'Enerji Yükleme', en: 'Energy Boost' },
    description: { tr: 'Sabah veya öğleden sonra enerji için', en: 'Morning or afternoon energy kick' },
    benefits: {
      tr: ['Uyanıklık', 'Odaklanma', 'Vücut aktivasyonu'],
      en: ['Alertness', 'Focus', 'Body activation'],
    },
    steps: [
      { id: 'e1', zoneId: 'kidney',     durationSeconds: 60, instruction: { tr: 'Böbrek bölgesini aktive edin — enerji merkezi', en: 'Activate kidney zone — energy center' }},
      { id: 'e2', zoneId: 'liver',      durationSeconds: 60, instruction: { tr: 'Karaciğer bölgesini uyarın', en: 'Stimulate liver zone' }},
      { id: 'e3', zoneId: 'lung',       durationSeconds: 60, instruction: { tr: 'Akciğer bölgesini açın — oksijen akışı', en: 'Open lung zone — oxygen flow' }},
      { id: 'e4', zoneId: 'brain',      durationSeconds: 60, instruction: { tr: 'Beyin bölgesini uyarın — uyanıklık', en: 'Stimulate brain zone — alertness' }},
      { id: 'e5', zoneId: 'pituitary',  durationSeconds: 45, instruction: { tr: 'Hipofiz noktasına basın — hormonal enerji', en: 'Press pituitary point — hormonal energy' }},
    ],
  },
  {
    id: 'digestion-relief',
    emoji: '🌿',
    category: 'digestion',
    isPremium: true,
    durationMinutes: 20,
    difficulty: 'intermediate',
    title: { tr: 'Sindirim Rahatlama', en: 'Digestion Relief' },
    description: { tr: 'Mide ve bağırsak sorunları için kapsamlı seans', en: 'Comprehensive session for stomach & gut issues' },
    benefits: {
      tr: ['Hazımsızlık giderme', 'Bağırsak hareketi', 'Şişkinlik azaltma'],
      en: ['Indigestion relief', 'Bowel movement', 'Bloating reduction'],
    },
    steps: [
      { id: 'd1', zoneId: 'stomach',   durationSeconds: 90,  instruction: { tr: 'Mide bölgesini saat yönünde masaj yapın', en: 'Massage stomach zone clockwise' }},
      { id: 'd2', zoneId: 'liver',     durationSeconds: 60,  instruction: { tr: 'Karaciğeri uyarın — sindirim enzimleri', en: 'Stimulate liver — digestive enzymes' }},
      { id: 'd3', zoneId: 'intestine', durationSeconds: 120, instruction: { tr: 'Bağırsak bölgesinde spiral hareket yapın', en: 'Spiral movement on intestinal zone' }},
      { id: 'd4', zoneId: 'kidney',    durationSeconds: 60,  instruction: { tr: 'Böbrekleri aktive edin — toksin atımı', en: 'Activate kidneys — toxin removal' }},
    ],
  },
  {
    id: 'full-body',
    emoji: '🦶',
    category: 'full',
    isPremium: true,
    durationMinutes: 45,
    difficulty: 'advanced',
    title: { tr: 'Tam Vücut Refleks', en: 'Full Body Reflex' },
    description: { tr: 'Tüm sistemi kapsayan premium seans', en: 'Premium session covering all systems' },
    benefits: {
      tr: ['Bütünsel denge', 'Derin detoks', 'Enerji sıfırlama'],
      en: ['Holistic balance', 'Deep detox', 'Energy reset'],
    },
    steps: [
      { id: 'f1', zoneId: 'brain',      durationSeconds: 60,  instruction: { tr: 'Beyin ile başlayın', en: 'Start with brain' }},
      { id: 'f2', zoneId: 'sinus',      durationSeconds: 45,  instruction: { tr: 'Sinüsler', en: 'Sinuses' }},
      { id: 'f3', zoneId: 'neck',       durationSeconds: 60,  instruction: { tr: 'Boyun', en: 'Neck' }},
      { id: 'f4', zoneId: 'lung',       durationSeconds: 60,  instruction: { tr: 'Akciğerler', en: 'Lungs' }},
      { id: 'f5', zoneId: 'heart',      durationSeconds: 45,  instruction: { tr: 'Kalp', en: 'Heart' }},
      { id: 'f6', zoneId: 'stomach',    durationSeconds: 60,  instruction: { tr: 'Mide', en: 'Stomach' }},
      { id: 'f7', zoneId: 'liver',      durationSeconds: 60,  instruction: { tr: 'Karaciğer', en: 'Liver' }},
      { id: 'f8', zoneId: 'kidney',     durationSeconds: 60,  instruction: { tr: 'Böbrekler', en: 'Kidneys' }},
      { id: 'f9', zoneId: 'intestine',  durationSeconds: 90,  instruction: { tr: 'Bağırsaklar', en: 'Intestines' }},
      { id: 'f10', zoneId: 'spine',     durationSeconds: 90,  instruction: { tr: 'Omurga', en: 'Spine' }},
      { id: 'f11', zoneId: 'sciatic',   durationSeconds: 60,  instruction: { tr: 'Siyatik sinir', en: 'Sciatic nerve' }},
      { id: 'f12', zoneId: 'shen_men',  durationSeconds: 120, instruction: { tr: 'Shen Men ile bitirin', en: 'Finish with Shen Men' }},
    ],
  },
];
